### ISSUE TITLE
Add Player List UI

### ISSUE THREAD

**Issue by PhantomGamers** [NebulaModTeam/nebula#390]
Add an interface so players can see a list of other players in the same session.

The interface should also include:
* Pings
* A kick button and a ban button for the host
* The star system the players are in and their planet (if applicable)

**Comment by Needix** [comment]
Starting to work on it

**Comment by hubastard** [comment]
You might want to wait for #394 to be merged. I'm currently fixing the PR to be able to merge this today. Because that will change a lot of stuff in the project structure.

**Comment by Needix** [comment]
Okay i will start, but only prototype it, to find out how to approach this best

**Comment by hubastard** [comment]
Ok the merge is done.

**Comment by Needix** [comment]
Thank you

**Comment by sp00ktober** [comment]
implemented as chat command, so im gonna close this.

**Comment by PhantomGamers** [comment]
This should still be implemented as an in-game scoreboard-like UI IMO, that was the initial intention of the issue.
