### ISSUE TITLE
Belt mouseover highlight state stuck on for non-host players

### ISSUE THREAD

**Issue by Dournbrood** [NebulaModTeam/nebula#398]
Saw that nobody else has reported this graphical error.
How to reproduce:  
1. Connect to remote host as client, mouse over a belt either in standard view or deconstruction mode. 
2. Belt is now permanently highlighted!

![image](https://user-images.githubusercontent.com/19560915/126875964-e8edbddf-2532-43be-b8ef-75fd6235c0c0.png)

Can only be fixed by rejoining the game,

**Comment by NoGTNoHappy** [comment]
I can't reproduce this with that two steps unfortunately..
