### ISSUE TITLE
Wireless charging effect persists on client after leaving the charge area

### ISSUE THREAD

**Issue by decPL** [NebulaModTeam/nebula#448]
Just started playing recently (using latest version 0.6.0), my friend hosting and me joining the game. We've noticed today that the wireless charging effect (i.e. a large positive energy intake) from the wireless tower seems to persist on me (client) even after leaving the tower's area of effect - and it was up for a longer time (~5 minutes?).

Repro: join as a client, walk to a Wireless Power Tower to initiate mech charging, leave the tower area of effect, higlight mech core power indicator to see the charging value is still applied. Doesn't seem random at all - happened each and every time (at least since I've noticed this).

Let me know if I can provide any more details/logs/test this further.

**Comment by JKTKops** [comment]
I can confirm this. Disconnecting and reconnecting always restores correct charging status. It also seems more frequent when the host and client are on the same planet.

**Comment by EL-S** [comment]
Can confirm this is still an issue. It doesn't happen every time, but it occured at least once as a client in the early game and I enjoyed infinite flying with the mecha fuel not being used at all.
