### ISSUE TITLE
Energy consumption from dyson sphere rapidly spiking for client

### ISSUE THREAD

**Issue by jvdwetering** [NebulaModTeam/nebula#605]
In our save, when a client looks at the power consumption of the dyson sphere, it looks like it rapidly spikes, before resetting down to the normal amount and climbing up again. This even occurs when a single Ray Receiver is active. The Ray Receiver itself says it is consuming the normal amount, but the total requested power consumption rapidly goes up (into the gigawatts for just a single Ray Receiver). If this causes the total requested power to go over the limit of the dyson sphere, then the client sees the production of Critical Photons go down.
This is all just Client Side though. Everything works correctly on the server side. It does make it impossible for the client to see what the actual power draw is of the Ray Receivers, and the outputs of them are also not correctly displayed.
We could provide a save if necessary.
We are using one other mod, MoreMegaStructure, although we haven't yet build anything that it is included in the mod.

**Comment by starfi5h** [comment]
MoreMegaStructure has Dyson power patches that conflict with Nebula multiplayer mod. You'll need to install [NebulaCompatibilityAssist](https://dsp.thunderstore.io/package/starfi5h/NebulaCompatibilityAssist/) to fix the issue and make MoreMegaStructure compatible with Nebula.
You can attach the log file if that doesn't solve the issue. In mod manager settings -> Browse profile folder -> `BepInEx\LogOutput.log`
