### ISSUE TITLE
Warper slot not available for connected client

### ISSUE THREAD

**Issue by kotomaxibon** [NebulaModTeam/nebula#609]
Drive engine level 4 technology is unlocked but there is no slot for warper in the fuel chamber. The host has the slot and can use warp normally.
![image](https://github.com/hubastard/nebula/assets/32869933/a957e653-cd87-4f22-abb4-cfbfb182d71f)

**Comment by starfi5h** [comment]
Can't reproduce it with only Nebula 0.8.14 and its dependencies.
Try to let clients reconnect, it should solve the issue.
