### ISSUE TITLE
Nebula does not work with 0.10.x

### ISSUE THREAD

**Issue by joelimgu** [NebulaModTeam/nebula#617]
The game works fine on linux using proton, but after installing the mod I get this error (proton 8.0-4 and experimental):

```
An error has occurred! Game version 0.10.28.20779
8 Mods used: [IlLine1.0.0] [LDBTool3.0.1] [DSP Mod Save1.1.4] [DSP Common API1.5.7.0] [NebulaMultiplayerMod0.8.14.3] [NebulaMultiplayerModApi1.3.1.3] [BulletTime1.2.14] [Common API Nebula Compatibility1.5.7.0] 
[Nebula Error] System.TypeLoadException: Could not resolve type with token 010000dd (from typeref, class/assembly StringProto, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
  at CommonAPI.Systems.ProtoRegistry.RegisterString (System.String key, System.String enTrans) [0x00000] ;IL_0000 
  at NebulaPatcher.NebulaPlugin.RegisterKeyBinds () [0x0004b] ;IL_004B 
  at NebulaPatcher.NebulaPlugin.Initialize () [0x0000a] ;IL_000A 
  at NebulaPatcher.NebulaPlugin.Awake () [0x0037f] ;IL_037F 
```
```
An error has occurred! Game version 0.10.28.20779
8 Mods used: [IlLine1.0.0] [LDBTool3.0.1] [DSP Mod Save1.1.4] [DSP Common API1.5.7.0] [NebulaMultiplayerMod0.8.14.3] [NebulaMultiplayerModApi1.3.1.3] [BulletTime1.2.14] [Common API Nebula Compatibility1.5.7.0] 
MissingMethodException: void PlanetFactory.RemoveEntityWithComponents(int)
CommonAPI.Patches.GameMain_Patch.OnGameBegin ();(IL_0000)
GameMain.Begin ();(IL_0144)
GameLoader.FixedUpdate ();(IL_00E7)
```

**Comment by bckelly1** [comment]
I am seeing this as well, Windows 10 running Steam.

**Comment by Dessix** [comment]
Steam -> Game properties -> Betas -> 0.9.x latest until Nebula reverse-engineers compatibility with the new changes.

**Comment by Jessomadic** [comment]
The newest update was HUGE and had lots of code changes. If I had to guess it will be a bit before the mod is working on the newest version. Although there is a branch where they are working on it

**Comment by fozzibab** [comment]
Some kind of response from the developer would be extremely appreciated re: if this mod is still under development or not because...well, you know, hope. Thanks in advance 🙏

**Comment by Jessomadic** [comment]
It is. Look at the 10.0x branch

**Comment by adaliszk** [comment]
Probably would make sense to link https://github.com/NebulaModTeam/nebula/pull/616 and this ticket

**Comment by tibikuaile** [comment]
Very much looking forward to it, always keeping an eye on it，0.10.0

**Comment by YUME1Minami** [comment]
I am looking forward to running Nebula in version 0.10

**Comment by Dessix** [comment]
With the merger of #616, what are the remaining tasks to track? Is there a tag for work items blocking the next release with `0.10.x` support, or could someone with familiarity prepare a tracking issue for the remaining work?

**Comment by ADKaster** [comment]
@Dessix it seems that this discussion post lists the remaining work for getting the PVE content working with the mod. https://github.com/NebulaModTeam/nebula/discussions/646
