### ISSUE TITLE
BepInEx Version

### ISSUE THREAD

**Issue by momift** [NebulaModTeam/nebula#637]
Hi, I use Thunderstore Manager to install mods. Premised that due to many mods incompatible with version 0.10 of the game, I went back to persion 9.27.. 
What is happening: when I install the NebulaMultiplayerModApi mod, I have this error in the log [Warning:   BepInEx] Plugin [NebulaMultiplayerModApi 1.3.1.3] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update", but on Thunderstore Manager there is only version 5.4.17. How do I update it or use the latest version ? 

Thank you

**Comment by PhantomGamers** [comment]
This is a warning, not an error, and can safely be ignored.
