### ISSUE TITLE
Unable to launch the game properly！

### ISSUE THREAD

**Issue by myyyss** [NebulaModTeam/nebula#649]
![1](https://github.com/NebulaModTeam/nebula/assets/80999273/955da1f9-48c9-41c2-82d5-df4ba41f4634)
![2](https://github.com/NebulaModTeam/nebula/assets/80999273/65a838e5-ea62-41e3-a770-1dc021fc2639)
This is my mod version number and game version number, why can't I enter the game normally?

**Comment by starfi5h** [comment]
Nebula isn't updated to compatible yet.
Roll back the game version, or install the [pre-release version](https://nightly.link/NebulaModTeam/nebula/workflows/build-winx64/master/build-artifacts-Release.zip).
Duplicated to #617

**Comment by myyyss** [comment]
> Nebula 尚未更新为兼容。回滚游戏版本，或安装[预发布版本](https://nightly.link/NebulaModTeam/nebula/workflows/build-winx64/master/build-artifacts-Release.zip)。复制到 #617

Thank you very much, maybe you will receive my tip in the new version!
