### ISSUE TITLE
The effect of turning on sandbox mode will be retained in the branch of Black Mist Online

### ISSUE THREAD

**Issue by xiaojiuawa** [NebulaModTeam/nebula#656]
When creating an online game and activating battle mode, you will exit the game and load any save. At this time, you will also be in sandbox mode, and items will be manufactured immediately without the need for materials. Although technology is shown as not researched, in reality, the effects of technology do exist and will not disappear.

The game version and mod file I am using are as follows:
DSPGameVersion:0.10.29.21950
[plugins.zip](https://github.com/NebulaModTeam/nebula/files/14392809/plugins.zip)
The mod version is the latest compiled version currently available

**Comment by xiaojiuawa** [comment]
Additional supplements:
If the mod is deleted at this time, this phenomenon will stop, but adding the mod back to the game will crash during startup. Observing the logs, it is found that there is an error message as follows:
[Warning:NebulaMultiplayerMod] Discord.ResultException: InternalError
  at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags) [0x00331] in <bf286ee57477408ea5b73a7313c69288>:IL_0331 
  at NebulaWorld.SocialIntegration.DiscordManager.Setup (Discord.ActivityManager+ActivityJoinHandler activityJoinHandler) [0x00025] in <1f52569cd13b4b9588d96a4fe63287b7>:IL_0025

**Comment by xiaojiuawa** [comment]
额，就是在那个黑雾的分支下，如果你开过那个游戏的沙盒模式，然后你的普通游戏也会变成沙盒模式，甚至于你开的科技的效果都会保留，
关掉游戏再开游戏，游戏会直接崩掉了，报错日志就是第二条回复，我这里可以确定是存档出现了问题，我把游戏的存档挪走，然后问题就没有复现了。

**Comment by sk7725** [comment]
Bug reproduced in latest version as of now (0.9.1)

**Comment by starfi5h** [comment]
For future reference, there is a difference between the Release and Debug build
The Debug build will have some cheat functions
https://github.com/NebulaModTeam/nebula/wiki/Setting-up-a-development-environment#debug-build-difference
