### ISSUE TITLE
Dark Fog bug

### ISSUE THREAD

**Issue by ByboyCn** [NebulaModTeam/nebula#657]
Some of the current problems encountered:
1. The enemy will ignore Icarus and will not attack.

2. There are many enemies on the planet, but there is no one after landing. After entering the planetary view, it shows that there are still many.

https://github.com/NebulaModTeam/nebula/assets/17998816/d77f5dca-a408-4d39-a88f-34f435e5b7c8

**Comment by ByboyCn** [comment]
https://pan.baidu.com/s/1LwcoMEy9sk7_TcrfsH5cbA?pwd=hw7t

**Comment by starfi5h** [comment]
Does the error still persist after client reconnect?

**Comment by ByboyCn** [comment]
These problems occur a few seconds after reconnection.

**Comment by starfi5h** [comment]
Can you test if this version solve the red error message?
[NebulaMultiplayerMod_Preview168.zip](https://github.com/NebulaModTeam/nebula/files/14534090/NebulaMultiplayerMod_Preview168.zip)
