### ISSUE TITLE
Planetary Shield can't stop the Dark Fog Repeater from landing

### ISSUE THREAD

**Issue by SnowMoonSS** [NebulaModTeam/nebula#668]
When there are no players on the planet, the shield has no effect and the Dark Fog can still land. When I went to the planet, I found that its shield value was increasing. From xxM to xxG in a few seconds. It's a feature for saving network bandwidth or other things, or just a bug?

**Comment by SnowMoonSS** [comment]
![image](https://github.com/NebulaModTeam/nebula/assets/21017431/aa5694dd-99a4-46ae-92c6-680c01ab348e)
These are the MODs I installed.

**Comment by SnowMoonSS** [comment]
![d592147db017ec075f1a9285412db477](https://github.com/NebulaModTeam/nebula/assets/21017431/c975f2a0-8716-4ddc-882f-bd2182fcde14)
7 deployed Planetary Shield Generators cost 847MW, default difficulty, weird

**Comment by SnowMoonSS** [comment]
试了下0.9.3，无头服务器中的行星护盾仍然不能阻止黑雾中继器登陆。我自己做主机，行星护盾是能够阻挡黑雾中继器登陆的。

1. 我自己做主机开了个黑雾难度拉满的沙盒模式存档
2. 清理了脉冲星那颗行星上的所有黑雾基地
3. 平铺7个行星护盾，等待护盾能量充满。理论上这应该能阻挡黑雾登陆，单机模式中也确实阻挡了
4. 前往另一个恒星系，从星际地图观察脉冲星星系，等待一个黑雾中继器前往行星进行登陆
5. 在黑雾中继器即将登陆时存档
6. 观察到黑雾中继器返回黑雾巢穴，没能成功登陆行星
7. 将存档移动到无头服务器里并启动
8. 进入服务器
9. 观察到黑雾中继器成功登陆了脉冲星的那颗行星

另外，从一颗已经完全充满行星护盾能量的行星前往另一个恒星系再返回那颗行星，我发现行星护盾能量会重新开始充能

I tried 0.9.3, the planetary shield in the headless server still couldn't prevent the Dark Fog Repeaterfrom landing. I make my own host, and the planetary shield can block the Dark Fog Repeater from landing.

1. I made my own host and opened a sandbox mode archive with full Dark Fog difficulty.
2. Cleaned up all the black fog bases on the planet Pulsar
3. Lay out 7 planetary shields and wait for the shield energy to be filled. In theory, this should be able to block Dark Fog from landing, and it does block it in singleplayer mode.
4. Go to another star system, observe the pulsar system from the interstellar map, and wait for a Dark Fog Repeater to go to the planet for landing.
5. Save the game when the Dark Fog Repeater is about to land.
6. Observed that the Dark Fog Repeater returned to the Dark Fog Lair and failed to successfully land on the planet.
7. Move the save to the headless server and start it
8. Enter the server
9. The planet where the Dark Fog Repeater was observed successfully landing on the pulsar

Also, when traveling from a planet that was already fully charged with planetary shield energy to another star system and back to that planet, I found that the planetary shield energy starts to recharge again

**Comment by AlienXAXS** [comment]
To add to this, it seems that the sync also is a little off if the host mecha isnt on the planet where clients are attempting to generate threat.

**Comment by AlienXAXS** [comment]
Ive been looking into this with my own harmony patches to listen into what the relay is doing every tick.
I am unable to reproduce the problem here.

Did this get patched already?

Here is the test save i am using that has a relay heading to a planet which is shielded, and you can see it bounce away as it hits the shield.

[Save.zip](https://github.com/user-attachments/files/16202596/Save.zip)

**Comment by AlienXAXS** [comment]
I have been looking at this for awhile...
It seems to be in this section of code within DFRelayComponent, method TestRelayCondition.

When loading the game on headless, a planets ATField becomes broken as isEmpty is True, and Energy is zero but only on the headless game.

My tests are logging such information as you can see below:
**Client**
```
[Info   :NebulaHeadlessAssistant] RelaySailLogic -> Stage:0(IN_SPACE) Direction:1 RelayID:7 Owner:1000001 KeyFrame:True Target:101(CorLeonis I)
[Info   :NebulaHeadlessAssistant] RelaySailLogic S:0 (IN_SPACE) -> baseID is Zero, checking landing conditions for position -1.635254 265.6697 -48.13476
[Info   :NebulaHeadlessAssistant] TestRelayCondition fired for planet CorLeonis I!
[Info   :NebulaHeadlessAssistant] TestRelayCondition -> InstanceEmpty False InstanceEnergy:6508242535
[Info   :NebulaHeadlessAssistant] TestRelayCondition -> Instance is spherical, aborting (Return false)
[Info   :NebulaHeadlessAssistant] CheckLandCondition for relay 7 -> Planet has shield, TestRelayCondition result: False
[Info   :NebulaHeadlessAssistant] RelaySailLogic S:0 (IN_SPACE) -> Is 74174962.9315746 < 360000?
[Info   :NebulaHeadlessAssistant] RelaySailLogic S:0 (IN_SPACE) -> We are too far away from the planet, keep searching.
```

**Headless**
```
[Info   :NebulaHeadlessAssistant] RelaySailLogic -> Stage:0(IN_SPACE) Direction:1 RelayID:7 Owner:1000001 KeyFrame:True Target:101(CorLeonis I)
[Info   :NebulaHeadlessAssistant] RelaySailLogic S:0 (IN_SPACE) -> baseID is Zero, checking landing conditions for position -206.0041 54.74409 165.7269
[Info   :NebulaHeadlessAssistant] TestRelayCondition fired for planet CorLeonis I!
[Info   :NebulaHeadlessAssistant] TestRelayCondition -> InstanceEmpty True InstanceEnergy:0
```
Note: most of these messages are manual logs from RelaySailLogic

Notice how the headless server is not checking the distance to the planet, whereas the client is.  This is the biggest problem here as the above check fails causing the code to never go down the correct path where planet shields are checked, and eventually the Relay is told to return back to it's dock within the hive.

I am happy to share video or have a discord chat about this, but i will keep digging.

**Comment by AlienXAXS** [comment]
The following code addition (albeit from another bepinex plugin) seems to work to fix this problem.

```csharp
[HarmonyPrefix,HarmonyPatch(typeof(PlanetATField), nameof(PlanetATField.RecalculatePhysicsShape))]
        public static bool RecalculatePhysicsShape_Prefix(PlanetATField __instance)
        {
            // If we're the server, let's do some stuff manually!
            if (NebulaHeadlessAssistant.Instance.IsDedicated)
            {
                if (__instance.generatorCount == 0)
                {
                    __instance.ClearPhysics();
                    __instance.energyMaxTarget = 0L;
                }
                
                __instance.CreatePhysics();
                __instance.isSpherical = true;

                /*
                 * This is usually computed on the GPU, No idea what math the GPU does, so we're shoving 0.95 here.
                 * On my own testing this goes as low as 0.35 during initial planet shield spin up
                 * and when it hits 1.0 it seems to stop calling this method.
                 */
                __instance.energyMaxTarget = (long)(1200000000000.0 * 0.95 + 0.5);

                if (__instance.energy > 0)
                {
                    __instance.isEmpty = false;
                }

                // I believe these are used in raycasting tests to see if a relay would hit a shield, so we need them.
                if (__instance.colliderHotTicks > 0)
                    __instance.OpenColliderObject();
                else
                    __instance.CloseColliderObject();
                
                return false;
            }

            return true;
        }
```

However, as it's not possible to simulate what the GPU was doing at the time, it's not really possible to know what crazy math is involved to set the energyMaxTarget.  I did dump the value for awhile and it seems to be a float between 0.0 and 1.0. - It's possible that this is the size of the shield as it's charging.

Once the value hits 1.0f the method RecalculatePhysicsShape is no longer called as often, as it's no longer needed to recalculate it until something changes (such as another shield generator being put down).  I picked a high number so the headless server assumes the shields are attempting to always charge to their max state, but testing will be needed.

Known Weirdness:
- When a relay is viewed on a remote galaxy, it will appear as though the relay has landed, however it gets stuck in some repeating animation and im not too sure as to why.  When you visit the planet yourself the relay flies off as it should.

**Comment by SnowMoonSS** [comment]
Thank you guys, now it works！
