### ISSUE TITLE
[Headless] newgame

### ISSUE THREAD

**Issue by ByboyCn** [NebulaModTeam/nebula#671]
我想使用无根模式启动游戏,并且在上黑雾的设置,应该怎么做?

**Comment by ByboyCn** [comment]
[NebulaPlugin.cs](https://github.com/NebulaModTeam/nebula/blob/master/NebulaPatcher/NebulaPlugin.cs )当前不满足

**Comment by starfi5h** [comment]
在0.9.3后可以用-newgame-cfg参数, 它会产生nebulaGameDescSettings.cfg配置档。 之后可以调整其中的参数
