### ISSUE TITLE
can't setup headless server

### ISSUE THREAD

**Issue by Linwendong83** [NebulaModTeam/nebula#679]
[1.log](https://github.com/NebulaModTeam/nebula/files/15275189/1.log)
DSPGAME.exe -batchmode -nographics -server -load save1 -logFile 1.log

**Comment by starfi5h** [comment]
```
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
```
Make sure to create a [steam_appid.txt](https://github.com/starfi5h/nebula/files/8694015/steam_appid.txt) file in the root of the game directory (next to DSPGame.exe) with the text 1366540. And run Steam.exe in background in either online mode or offline mode.
