### ISSUE TITLE
Mod not compatible with new update

### ISSUE THREAD

**Issue by hitsukun17** [NebulaModTeam/nebula#680]
Mod not working with the new update going from 10.29 to 10.30 that was updated on 5/29/24. Thanks!

**Comment by Tuumke** [comment]
+follow

**Comment by SampsonFox** [comment]
+1

**Comment by starfi5h** [comment]
Yes. It will take a week or more to fix the mod.

In the meantime, you can try to revert the game to 0.10.29.22015 by using Steam console command 
`download_depot 1366540 1366541 5972978055842355887`
to download the old game content and overwrite the original one.

Or install the following pre-released version before the final version is released.

----
[NebulaMultiplayerMod_Preview_3_4.zip](https://github.com/user-attachments/files/15522220/NebulaMultiplayerMod_Preview_3_4.zip)
This is a local Thunderstore package (0.9.3.4+dbf14c4) that is compatible with game 0.10.30.22292, for people who can't revert the game version (e.g. Game Pass)
This early build may have bugs and desync, backup saves before using it.

**Installation:**
Open the mod manager and navigate to Settings.
In the Profile tab, locate and click on the "Import local mod" option.
then choose the zip file.
Return to the profile, and disable the original Nebula mod (0.9.3).

**Known issues:**
Ship animation don't show up in client
The new interstellar routes and related ILS features don't sync
The new belts tilted don't sync

**Comment by hitsukun17** [comment]
I found that you all had a discord server last night and joined it! Thank you for the reply and info!
