### ISSUE TITLE
Error when loading the save games

### ISSUE THREAD

**Issue by Kreijeck** [NebulaModTeam/nebula#691]
Since last week, I always get the following error, when I load any of our save games:

```ini
An error has occurred! Game version 0.10.30.22292 (Host)
8 Mods used: [IlLine1.0.0] [LDBTool3.0.1] [DSP Mod Save1.2.1] [DSP Common API1.6.5.0] [NebulaMultiplayerMod0.9.6.2] [NebulaMultiplayerModApi2.0.0.24] [BulletTime1.4.7] [Common API Nebula Compatibility1.6.5.0] 
[Nebula Error] System.InvalidOperationException: No process is associated with this object.
  at System.Diagnostics.Process.EnsureState (System.Diagnostics.Process+State state) [0x00018] ;IL_0018 
  at System.Diagnostics.Process.get_HasExited () [0x0000b] ;IL_000B 
  at NebulaNetwork.Ngrok.NgrokManager.IsNgrokActive () [0x0001b] ;IL_001B 
```

Then the games seems to work and everything works fine. But after ~ 1- 3h the game freezes and has to be restarted

**Comment by PhantomGamers** [comment]
Well if you aren't using the ngrok functionality you can just disable that in the nebula settings.

The freeze is probably a separate issue, but we'd need the BepInEx/LogOutput.log file to diagnose that

**Comment by Kreijeck** [comment]
Thanks for fast response.
We are using the ngrok functionality, so I shouldn't disable it.

When I next time get a freeze, I will add here the log.

**Comment by PhantomGamers** [comment]
You're saying that despite the error that says the ngrok process wasn't found, ngrok is actually running and working correctly?

Fully restarting your PC might solve that issue

**Comment by Kreijeck** [comment]
Yes exactly. I only get this error message, but it's possible to join the game with the "ngrok IP adress".

Full restart don't change anything :-/

**Comment by PhantomGamers** [comment]
Did you at some point install ngrok outside of nebula? It sounds to me like you're getting that error because another instance of ngrok is already running by the time nebula tries to launch its own, so it closes the new instance and then that error triggers because the process as launched by nebula no longer exists.

Then, if restarting doesn't change anything, I'd think that other instance is set to run on startup maybe.
