### ISSUE TITLE
300 MB Logfile in 2 Days

### ISSUE THREAD

**Issue by BananaAcid** [NebulaModTeam/nebula#705]
The BpInEx Logfile gets flodded with 

```log
[Warning:NebulaMultiplayerMod] Remote PlanetData.UpdateDirtyMesh: meshes[74] is null
```

As I am hosting it as a fully dedicated server (yes without steam client), parsing the logfile for getting currently connected users, the log got crazy long in a short time and would probably fill up the server in a short time.

Is it possible to reduce the log to stop logging repetitive messages?

<img width="1543" alt="image" src="https://github.com/user-attachments/assets/600c461a-1149-45cd-9a62-52c49b85baab">

**Comment by starfi5h** [comment]
In `BepInEx\config\BepInEx.cfg`, set Enables writing log messages to disk option to false in [Logging.Disk]

I wonder which other mods will cause this warning

**Comment by BananaAcid** [comment]
it worked by removing the 'warning' keyword from the Disk section, but it does not work for the Terminal section

**Comment by PhantomGamers** [comment]
> The other Dependency Mods do not log anything it seems - its all NebulaMod

Are you only running Nebula and its dependencies though, or other mods as well?

This log message is *from* Nebula but it could be caused by some other mod you have installed

**Comment by starfi5h** [comment]
The warning log is removed in v0.9.10
