### ISSUE TITLE
 [Nebula Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by emmahyde** [NebulaModTeam/nebula#707]
![IMG_6981](https://github.com/user-attachments/assets/622ba7f8-5366-4d5d-b891-20369cf8e0b7)
As of latest update. Client is getting it, host is not. Any hints as to why this might be occurring now? 

Sorry about the "screenshot", my friend did not know how to take one and is a grumpy old man. 😄

**Comment by starfi5h** [comment]
There is desync in space Dark Fog data, so the broadcast of kill event cause the error.
Just let the client reconnect.
