### ISSUE TITLE
A bug when use the nightly version for DSP 0.10.31.24646 update

### ISSUE THREAD

**Issue by CALMorACT** [NebulaModTeam/nebula#717]
When I use the production panel in `client` to make items, I get an error no matter what I make.

![屏幕截图 2024-12-03 154146](https://github.com/user-attachments/assets/72bc7329-32bf-41d8-84d7-659d36cc6368)

Mod used repo's commit id is `98a8fd461d8d6177d89488b61081f5a92b2cc215`

**Comment by starfi5h** [comment]
Can't reproduce
Try install the following link to download the latest pre-release version
 https://nightly.link/NebulaModTeam/nebula/workflows/build-winx64/master/build-artifacts-Release.zip
