### ISSUE TITLE
run with nographics server with cannot build

### ISSUE THREAD

**Issue by Shadow403** [NebulaModTeam/nebula#720]
![{EC3C2E3C-C5EF-4278-8B7A-5A4BD0AB7F59}](https://github.com/user-attachments/assets/60b608f9-df54-4976-a220-083ff8c30fe9)
![image](https://github.com/user-attachments/assets/dd62275d-c9a2-4492-ba3d-99a7bd88be98)
![image](https://github.com/user-attachments/assets/27782829-2e88-4d65-86f4-1c26940a320f)

game & mod all latest version
 when i use none-nographics to run server but i cannot build anythings

**Comment by starfi5h** [comment]
Toggle enable drone option in mecha panel (C)
![image](https://github.com/user-attachments/assets/b87cae77-674e-4cfd-a9ee-63e4293da60d)

**Comment by Shadow403** [comment]
> Toggle enable drone option in mecha panel (C)
> 
> ![image](https://github.com/user-attachments/assets/b87cae77-674e-4cfd-a9ee-63e4293da60d)
> 
> 

thanks so much😁
